### ISSUE TITLE
Influxdb

### ISSUE THREAD

**Issue by hugoboss00** [rp-/tigo-exporter#1]
How to export to Influxdb? 
Is there a possibility to do so?

**Comment by rp-** [comment]
tl;dr: no

I never worked with influxdb yet, but as far as I understand it uses a PUSH model.

This exporter uses the default prometheus PULL model, so theoretically it would be possible to also
push data to influxdb on a timer, but I think a program specifically for that purpose would be better.
As it doesn't need the http server library and just a client, to push to influxdb.

Someone could either fork this project and add/change that, or we make a library out of it, sharing the csv parsing part.

**Comment by rp-** [comment]
https://github.com/guglicap/tigo-influx-exporter
